### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by ghost** [JettChenT/SSBS-PC#1]
Jett
Projects is a poop function
Don't use it
**Please...**

**Comment by ghost** [comment]
Jett
Your description is too long
And you don't have a link
**Please...**

**Comment by ghost** [comment]
Never mind projects
It's good
:joy:

**Comment by ghost** [comment]
But not many people *use* it anyway.

**Comment by JettChenT** [comment]
Wow! you changed your mind in 3 hours! That's fast!

**Comment by JettChenT** [comment]
> Jett
> Your description is too long
> And you don't have a link
> **Please...**

I haven't deployed it yet.

**Comment by ghost** [comment]
> Wow! you changed your mind in 3 hours! That's fast!

Hey! I'm getting *annoyed*

> > Jett
> > Your description is too long
> > And you don't have a link
> > **Please...**
> 
> I haven't deployed it yet.

I saw your ssbs-vp.herokuapp.com.
Thanks for using heroku :+1:
