### ISSUE TITLE
deploying issue

### ISSUE THREAD

**Issue by JettChenT** [JettChenT/SSBS-PC#3]
I tried to deploy, but the error comes up:

ID 5dda70e7-1403-4c03-8231-f3c02c27a591
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed
```

**Comment by ghost** [comment]
No one is going to see your code except me

**Jett**

**Comment by JettChenT** [comment]
I fixed it

**Comment by ghost** [comment]
How? I would like to know
*Please*
